export const jobs_applied = [
  {
    id: "1",
    Title: "Software Engineer",
    location: "San Francisco, CA",
    offer_salary: "120000",
    application_method: "Online",
    url_job: "https://www.example.com/job/1",
    current_status: "Applied",
    user_id: "1",
    resumé: "",
    job_description: "",
    company_name: "ABC Inc.",
    created_at: "2023-04-02 10:00:00",
    updated_at: "2023-04-02 10:00:00",
  },
  {
    id: "2",
    Title: "Marketing Specialist",
    location: "New York, NY",
    offer_salary: "80000",
    application_method: "Referral",
    url_job: "https://www.example.com/job/2",
    current_status: "Interviewing",
    user_id: "1",
    resumé: "",
    job_description: "",
    company_name: "XYZ Corp.",
    created_at: "2023-04-01 12:00:00",
    updated_at: "2023-04-01 12:00:00",
  },
  {
    id: "3",
    Title: "Project Manager",
    location: "Seattle, WA",
    offer_salary: "110000",
    application_method: "In-Person",
    url_job: "https://www.example.com/job/3",
    current_status: "Rejected",
    user_id: "2",
    resumé: "",
    job_description: "",
    company_name: "LMN Co.",
    created_at: "2023-03-31 14:00:00",
    updated_at: "2023-03-31 14:00:00",
  },
  {
    id: "4",
    Title: "Sales Associate",
    location: "Chicago, IL",
    offer_salary: "60000",
    application_method: "Online",
    url_job: "https://www.example.com/job/4",
    current_status: "Offer Received",
    user_id: "3",
    resumé: "",
    job_description: "",
    company_name: "PQR Inc.",
    created_at: "2023-03-29 09:00:00",
    updated_at: "2023-03-29 09:00:00",
  },
  {
    id: "5",
    Title: "Graphic Designer",
    location: "Los Angeles, CA",
    offer_salary: "90000",
    application_method: "Online",
    url_job: "https://www.example.com/job/5",
    current_status: "Applied",
    user_id: "4",
    resumé: "",
    job_description: "",
    company_name: "STU Co.",
    created_at: "2023-03-28 16:00:00",
    updated_at: "2023-03-28 16:00:00",
  },
  {
    id: "6",
    Title: "Product Manager",
    location: "Boston, MA",
    offer_salary: "130000",
    application_method: "Online",
    url_job: "https://www.example.com/job/6",
    current_status: "Interviewing",
    user_id: "5",
    resumé: "",
    job_description: "",
    company_name: "VWX Corp.",
    created_at: "2023-03-25 10:00:00",
    updated_at: "2023-03-25 10:00"
  }
];